version: 2
jobs:
  branches:
      only:
        - master
    docker:
      - image: circleci/slim-base
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout
      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - deploy:
          name: deploy to AWS
          command: |
              aws s3 sync ~/project \
              s3://userlandassetssupport --delete --exclude=".git/*"
